language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libgtest-dev

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install googletest; fi

script:
  - make all
  - make test
